/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.isimple.intelijpos_lite.ui.sale.sub;

import com.isimple.intelijpos_lite.hw.LineDisplay;
import com.isimple.intelijpos_lite.models.Receipt;
import com.isimple.intelijpos_lite.ui.main.UIHome;
import com.isimple.intelijpos_lite.util.Const;
import com.isimple.intelijpos_lite.util.Utilities;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dumidu
 */
public class UIPaymentInfo extends javax.swing.JDialog {

    private final double mValue;
    private final List<Receipt> mRECEIPTS;
    private PaymentSatus mPaymentStatus = PaymentSatus.PAYMENT_INCOMPLETE;
    private PaymentMethod mPaymentMethod = PaymentMethod.PAY_CASH;
    private double mDiscountValue = 0;
    private double mPaidValue = 0;
    private double mBalanceValue = 0;

    /**
     * Creates new form UIPaymentInfo
     *
     * @param parent
     * @param value
     */
    public UIPaymentInfo(UIHome parent, double value) {
        super(parent, true);
        initComponents();
        this.mValue = value;
        mRECEIPTS = new ArrayList<>();
        mTotal.setValue(value);
        setLocationRelativeTo(parent);
        mPay.requestFocus();
        LineDisplay.showMessage("Total : ", Const.CURRANCY + value, "", "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        mCash = new javax.swing.JToggleButton();
        mCard = new javax.swing.JToggleButton();
        mCredit = new javax.swing.JToggleButton();
        mCheque = new javax.swing.JToggleButton();
        mVoucher = new javax.swing.JToggleButton();
        mFree = new javax.swing.JToggleButton();
        mDiscount = new javax.swing.JToggleButton();
        mOther = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        mPay = new javax.swing.JFormattedTextField();
        mBackspace = new javax.swing.JButton();
        m7 = new javax.swing.JButton();
        m8 = new javax.swing.JButton();
        m9 = new javax.swing.JButton();
        mDelete = new javax.swing.JButton();
        m6 = new javax.swing.JButton();
        m5 = new javax.swing.JButton();
        m4 = new javax.swing.JButton();
        m1 = new javax.swing.JButton();
        m2 = new javax.swing.JButton();
        m3 = new javax.swing.JButton();
        mEnter = new javax.swing.JButton();
        mFlotingPoint = new javax.swing.JButton();
        m0 = new javax.swing.JButton();
        mOk = new javax.swing.JButton();
        mCancel = new javax.swing.JButton();
        mReset = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        mTotalPayment = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mTotal = new javax.swing.JFormattedTextField();
        mDuePayment = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mBalance = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mPaymentDetails = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Method"));

        buttonGroup1.add(mCash);
        mCash.setSelected(true);
        mCash.setText("Cash");
        mCash.setFocusable(false);
        mCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCashActionPerformed(evt);
            }
        });

        buttonGroup1.add(mCard);
        mCard.setText("Card");
        mCard.setFocusable(false);
        mCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCardActionPerformed(evt);
            }
        });

        buttonGroup1.add(mCredit);
        mCredit.setText("Credit");
        mCredit.setFocusable(false);
        mCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCreditActionPerformed(evt);
            }
        });

        buttonGroup1.add(mCheque);
        mCheque.setText("Cheque");
        mCheque.setFocusable(false);
        mCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mChequeActionPerformed(evt);
            }
        });

        buttonGroup1.add(mVoucher);
        mVoucher.setText("Voucher");
        mVoucher.setFocusable(false);
        mVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mVoucherActionPerformed(evt);
            }
        });

        buttonGroup1.add(mFree);
        mFree.setText("Free");
        mFree.setFocusable(false);
        mFree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFreeActionPerformed(evt);
            }
        });

        buttonGroup1.add(mDiscount);
        mDiscount.setText("Discount");
        mDiscount.setFocusable(false);
        mDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDiscountActionPerformed(evt);
            }
        });

        buttonGroup1.add(mOther);
        mOther.setText("Other");
        mOther.setFocusable(false);
        mOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mOtherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mCard)
                    .addComponent(mCredit)
                    .addComponent(mCash, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mDiscount))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mCheque)
                    .addComponent(mVoucher)
                    .addComponent(mFree)
                    .addComponent(mOther))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {mCard, mCash, mCheque, mCredit, mDiscount, mFree, mOther, mVoucher});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mCash, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mCheque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mCard)
                    .addComponent(mVoucher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mCredit)
                    .addComponent(mFree))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mDiscount)
                    .addComponent(mOther))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {mCard, mCash, mCheque, mCredit, mDiscount, mFree, mOther, mVoucher});

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mPay.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        mPay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        mPay.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        mPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPayActionPerformed(evt);
            }
        });

        mBackspace.setText("←");
        mBackspace.setFocusable(false);
        mBackspace.setPreferredSize(new java.awt.Dimension(75, 50));
        mBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBackspaceActionPerformed(evt);
            }
        });

        m7.setText("7");
        m7.setFocusable(false);
        m7.setPreferredSize(new java.awt.Dimension(75, 50));
        m7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m7ActionPerformed(evt);
            }
        });

        m8.setText("8");
        m8.setFocusable(false);
        m8.setPreferredSize(new java.awt.Dimension(75, 50));
        m8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m8ActionPerformed(evt);
            }
        });

        m9.setText("9");
        m9.setFocusable(false);
        m9.setPreferredSize(new java.awt.Dimension(75, 50));
        m9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m9ActionPerformed(evt);
            }
        });

        mDelete.setText("⌫");
        mDelete.setFocusable(false);
        mDelete.setPreferredSize(new java.awt.Dimension(75, 50));
        mDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDeleteActionPerformed(evt);
            }
        });

        m6.setText("6");
        m6.setFocusable(false);
        m6.setPreferredSize(new java.awt.Dimension(75, 50));
        m6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m6ActionPerformed(evt);
            }
        });

        m5.setText("5");
        m5.setFocusable(false);
        m5.setPreferredSize(new java.awt.Dimension(75, 50));
        m5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m5ActionPerformed(evt);
            }
        });

        m4.setText("4");
        m4.setFocusable(false);
        m4.setPreferredSize(new java.awt.Dimension(75, 50));
        m4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m4ActionPerformed(evt);
            }
        });

        m1.setText("1");
        m1.setFocusable(false);
        m1.setPreferredSize(new java.awt.Dimension(75, 50));
        m1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1ActionPerformed(evt);
            }
        });

        m2.setText("2");
        m2.setFocusable(false);
        m2.setPreferredSize(new java.awt.Dimension(75, 50));
        m2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2ActionPerformed(evt);
            }
        });

        m3.setText("3");
        m3.setPreferredSize(new java.awt.Dimension(75, 50));
        m3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m3ActionPerformed(evt);
            }
        });

        mEnter.setText("↩");
        mEnter.setFocusable(false);
        mEnter.setPreferredSize(new java.awt.Dimension(75, 50));
        mEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEnterActionPerformed(evt);
            }
        });

        mFlotingPoint.setText(".");
        mFlotingPoint.setFocusable(false);
        mFlotingPoint.setPreferredSize(new java.awt.Dimension(75, 50));
        mFlotingPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFlotingPointActionPerformed(evt);
            }
        });

        m0.setText("0");
        m0.setFocusable(false);
        m0.setPreferredSize(new java.awt.Dimension(50, 50));
        m0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mPay)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(m7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(m4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(m1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(m2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(m3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addComponent(m0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mFlotingPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {m9, mBackspace});

        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mPay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mBackspace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mFlotingPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(mEnter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mOk.setText("Ok");
        mOk.setFocusable(false);
        mOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mOkActionPerformed(evt);
            }
        });

        mCancel.setText("Cancel");
        mCancel.setFocusable(false);
        mCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCancelActionPerformed(evt);
            }
        });

        mReset.setText("Reset");
        mReset.setFocusable(false);
        mReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(mOk, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mReset, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {mCancel, mOk, mReset});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mReset, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mOk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {mCancel, mOk, mReset});

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mTotalPayment.setEditable(false);
        mTotalPayment.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        mTotalPayment.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        mTotalPayment.setText("0.00");
        mTotalPayment.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        mTotalPayment.setEnabled(false);
        mTotalPayment.setFocusable(false);
        mTotalPayment.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setText("Total Payments");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel5.setText("Total");

        mTotal.setEditable(false);
        mTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        mTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        mTotal.setText("0.00");
        mTotal.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        mTotal.setEnabled(false);
        mTotal.setFocusable(false);
        mTotal.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

        mDuePayment.setEditable(false);
        mDuePayment.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        mDuePayment.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        mDuePayment.setText("0.00");
        mDuePayment.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        mDuePayment.setEnabled(false);
        mDuePayment.setFocusable(false);
        mDuePayment.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel6.setText("Due Payments");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel7.setText("Balance");

        mBalance.setEditable(false);
        mBalance.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        mBalance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        mBalance.setText("0.00");
        mBalance.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        mBalance.setEnabled(false);
        mBalance.setFocusable(false);
        mBalance.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(37, 37, 37)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mDuePayment)
                    .addComponent(mTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mTotalPayment, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(mTotalPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(mTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(mDuePayment, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(mBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mPaymentDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Method", "Ref", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mPaymentDetails.setRowHeight(30);
        jScrollPane1.setViewportView(mPaymentDetails);
        if (mPaymentDetails.getColumnModel().getColumnCount() > 0) {
            mPaymentDetails.getColumnModel().getColumn(0).setPreferredWidth(50);
            mPaymentDetails.getColumnModel().getColumn(1).setPreferredWidth(100);
            mPaymentDetails.getColumnModel().getColumn(2).setPreferredWidth(100);
            mPaymentDetails.getColumnModel().getColumn(3).setPreferredWidth(200);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCashActionPerformed
        mPaymentMethod = PaymentMethod.PAY_CASH;
    }//GEN-LAST:event_mCashActionPerformed

    private void mOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mOkActionPerformed
        paymentComplete();
    }//GEN-LAST:event_mOkActionPerformed

    private void m7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m7ActionPerformed
        mPay.setText(mPay.getText() + "7");
    }//GEN-LAST:event_m7ActionPerformed

    private void m8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m8ActionPerformed
        mPay.setText(mPay.getText() + "8");
    }//GEN-LAST:event_m8ActionPerformed

    private void m9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m9ActionPerformed
        mPay.setText(mPay.getText() + "9");
    }//GEN-LAST:event_m9ActionPerformed

    private void m4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m4ActionPerformed
        mPay.setText(mPay.getText() + "4");

    }//GEN-LAST:event_m4ActionPerformed

    private void m5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m5ActionPerformed
        mPay.setText(mPay.getText() + "5");
    }//GEN-LAST:event_m5ActionPerformed

    private void m6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m6ActionPerformed
        mPay.setText(mPay.getText() + "6");
    }//GEN-LAST:event_m6ActionPerformed

    private void m1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1ActionPerformed
        mPay.setText(mPay.getText() + "1");
    }//GEN-LAST:event_m1ActionPerformed

    private void m2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2ActionPerformed
        mPay.setText(mPay.getText() + "2");
    }//GEN-LAST:event_m2ActionPerformed

    private void m3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m3ActionPerformed
        mPay.setText(mPay.getText() + "3");
    }//GEN-LAST:event_m3ActionPerformed

    private void m0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m0ActionPerformed
        mPay.setText(mPay.getText() + "0");
    }//GEN-LAST:event_m0ActionPerformed

    private void mFlotingPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFlotingPointActionPerformed
        mPay.setText(mPay.getText() + ".");
    }//GEN-LAST:event_mFlotingPointActionPerformed

    private void mEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEnterActionPerformed
        addPaymentDetail();
    }//GEN-LAST:event_mEnterActionPerformed

    private void mDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDeleteActionPerformed
        mPay.setText("");
    }//GEN-LAST:event_mDeleteActionPerformed

    private void mBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBackspaceActionPerformed
        if (!mPay.getText().isEmpty()) {
            mPay.setText(mPay.getText().substring(0, mPay.getText().length() - 1));
        }
    }//GEN-LAST:event_mBackspaceActionPerformed

    private void mChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mChequeActionPerformed
        mPaymentMethod = PaymentMethod.PAY_CHEQUE;
    }//GEN-LAST:event_mChequeActionPerformed

    private void mCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCardActionPerformed
        mPaymentMethod = PaymentMethod.PAY_CARD;
    }//GEN-LAST:event_mCardActionPerformed

    private void mVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mVoucherActionPerformed
        mPaymentMethod = PaymentMethod.PAY_VOUCHER;
    }//GEN-LAST:event_mVoucherActionPerformed

    private void mCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCreditActionPerformed
        mPaymentMethod = PaymentMethod.PAY_CREDIT;
    }//GEN-LAST:event_mCreditActionPerformed

    private void mFreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFreeActionPerformed
        mPaymentMethod = PaymentMethod.PAY_FREE;
    }//GEN-LAST:event_mFreeActionPerformed

    private void mDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDiscountActionPerformed
        mPaymentMethod = PaymentMethod.PAY_DISCOUNT;
    }//GEN-LAST:event_mDiscountActionPerformed

    private void mOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mOtherActionPerformed
        mPaymentMethod = PaymentMethod.PAY_OTHER;
    }//GEN-LAST:event_mOtherActionPerformed

    private void mPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPayActionPerformed
        addPaymentDetail();
    }//GEN-LAST:event_mPayActionPerformed

    private void mResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mResetActionPerformed
        resetAll();
    }//GEN-LAST:event_mResetActionPerformed

    private void mCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCancelActionPerformed
        resetAll();
        this.dispose();
    }//GEN-LAST:event_mCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton m0;
    private javax.swing.JButton m1;
    private javax.swing.JButton m2;
    private javax.swing.JButton m3;
    private javax.swing.JButton m4;
    private javax.swing.JButton m5;
    private javax.swing.JButton m6;
    private javax.swing.JButton m7;
    private javax.swing.JButton m8;
    private javax.swing.JButton m9;
    private javax.swing.JButton mBackspace;
    private javax.swing.JFormattedTextField mBalance;
    private javax.swing.JButton mCancel;
    private javax.swing.JToggleButton mCard;
    private javax.swing.JToggleButton mCash;
    private javax.swing.JToggleButton mCheque;
    private javax.swing.JToggleButton mCredit;
    private javax.swing.JButton mDelete;
    private javax.swing.JToggleButton mDiscount;
    private javax.swing.JFormattedTextField mDuePayment;
    private javax.swing.JButton mEnter;
    private javax.swing.JButton mFlotingPoint;
    private javax.swing.JToggleButton mFree;
    private javax.swing.JButton mOk;
    private javax.swing.JToggleButton mOther;
    private javax.swing.JFormattedTextField mPay;
    private javax.swing.JTable mPaymentDetails;
    private javax.swing.JButton mReset;
    private javax.swing.JFormattedTextField mTotal;
    private javax.swing.JFormattedTextField mTotalPayment;
    private javax.swing.JToggleButton mVoucher;
    // End of variables declaration//GEN-END:variables

    public PaymentSatus getPaymentStatus() {
        return this.mPaymentStatus;
    }

    private void paymentComplete() {
        if (!mRECEIPTS.isEmpty() && (Double.parseDouble(mTotalPayment.getText().replaceAll(",", "")) >= mValue)) {
            mPaymentStatus = PaymentSatus.PAYMENT_COMPLETE;
            this.dispose();
        }
    }

    private void addPaymentDetail() {
        if (Double.parseDouble(mPay.getText()) > 0) {
            String ref = " ";
            Receipt receipt = new Receipt();
            if ((mPaymentMethod != PaymentMethod.PAY_CASH) && (mPaymentMethod != PaymentMethod.PAY_DISCOUNT)){
                String string = null;
                do {
                    string = JOptionPane.showInputDialog(this, "Input reference ?", "Input", JOptionPane.QUESTION_MESSAGE);
                } while (string.isEmpty());
                ref = string;
            }
            receipt.setMethod(mPaymentMethod.getValue());
            receipt.setRef(ref);
            receipt.setValue(Double.parseDouble(mPay.getText().replaceAll(",", "")));
            mRECEIPTS.add(receipt);
            double total = refreshPayments();
            mPay.setText("");
            mCash.setSelected(true);
            mPaymentMethod = PaymentMethod.PAY_CASH;
            LineDisplay.showMessage("Total : ", Const.CURRANCY + mValue, "Paid : ", Const.CURRANCY + (total - mDiscountValue));
        }
    }

    private double refreshPayments() {
        Utilities.clear(mPaymentDetails);
        DefaultTableModel model = (DefaultTableModel) mPaymentDetails.getModel();
        double total = 0;
        mDiscountValue = 0;
        for (int i = 0; i < mRECEIPTS.size(); i++) {
            Receipt receipt = mRECEIPTS.get(i);
            Object[] os = new Object[4];
            os[0] = i;
            os[1] = PaymentMethod.getMethod(receipt.getMethod());
            os[2] = receipt.getRef();
            os[3] = receipt.getValue();
            total += receipt.getValue();
            model.addRow(os);
            if (receipt.getMethod() == PaymentMethod.PAY_DISCOUNT.getValue()) {
                mDiscountValue += receipt.getValue();
            }
        }
        mTotalPayment.setValue(total);
        double due = mValue - total;
        if (due >= 0) {
            mDuePayment.setValue(due);
        } else {
            mDuePayment.setValue(0);
        }

        if (due < 0) {
            mBalance.setValue(-due);
        } else {
            mBalance.setValue(0);
        }
        mBalanceValue = Double.parseDouble(mBalance.getValue().toString());
        mPaidValue = Double.parseDouble(mTotalPayment.getValue().toString());
        return total;
    }

    private void resetAll() {
        mPaymentStatus = PaymentSatus.PAYMENT_INCOMPLETE;
        mPaymentMethod = PaymentMethod.PAY_CASH;
        mRECEIPTS.clear();
        refreshPayments();
    }

    public static enum PaymentSatus {

        PAYMENT_INCOMPLETE, PAYMENT_COMPLETE
    }

    private enum PaymentMethod {

        PAY_CASH(0),
        PAY_CARD(1),
        PAY_CREDIT(2),
        PAY_CHEQUE(3),
        PAY_VOUCHER(4),
        PAY_FREE(5),
        PAY_OTHER(6),
        PAY_DISCOUNT(7);

        private final int type;

        private PaymentMethod(int type) {
            this.type = type;
        }

        public int getValue() {
            return type;
        }

        public static String getMethod(int value) {
            switch (value) {
                case 0:
                    return "CASH";
                case 1:
                    return "CARD";
                case 2:
                    return "CREDIT";
                case 3:
                    return "CHEQUE";
                case 4:
                    return "VOUCHER";
                case 5:
                    return "FREE";
                case 6:
                    return "OTHER";
                case 7:
                    return "DISCOUNT";
            }
            return null;
        }

    }

    public List<Receipt> getReceipts() {
        return this.mRECEIPTS;
    }

    public double getDiscounts() {
        return this.mDiscountValue;
    }

    public double getPaymentValue() {
        return this.mPaidValue;
    }

    public double getBalanceValue() {
        return this.mBalanceValue;
    }
}
