/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.isimple.intelijpos_lite.ui.main;

import com.isimple.intelijpos_lite.models.User;
import com.isimple.intelijpos_lite.ui.barcode.UIBarcode;
import com.isimple.intelijpos_lite.ui.grn.UIGrn;
import com.isimple.intelijpos_lite.ui.login.UILogin;
import com.isimple.intelijpos_lite.ui.product.UIProductAdd;
import com.isimple.intelijpos_lite.ui.product.UIProductView;
import com.isimple.intelijpos_lite.ui.sale.UISale;
import com.isimple.intelijpos_lite.ui.statment.UIMiniStatment;
import com.isimple.intelijpos_lite.ui.stock.UIStocks;
import com.isimple.intelijpos_lite.ui.supplier.UISupplier;
import com.isimple.intelijpos_lite.util.Utilities;

/**
 *
 * @author dumidu
 */
public final class UIHome extends javax.swing.JFrame {

    private User mUser = null;

    /**
     * Creates new form UIHome
     */
    public UIHome() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setPreferredSize(java.awt.Toolkit.getDefaultToolkit().getScreenSize());
        setMaximumSize(java.awt.Toolkit.getDefaultToolkit().getScreenSize());
        setMinimumSize(java.awt.Toolkit.getDefaultToolkit().getScreenSize());
        jMenuBar1.setVisible(false);
        pnlConteiner.add(new UILogin(this));
        pnlConteiner.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlConteiner = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mCompany = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        mItem = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        mPurchase = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        mSales = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        mReturn = new javax.swing.JMenu();
        mLedger = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlConteiner.setLayout(new java.awt.BorderLayout());

        mCompany.setText("System");

        jMenuItem6.setText("Exit");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mCompany.add(jMenuItem6);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem8.setText("Drawer");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        mCompany.add(jMenuItem8);

        jMenuBar1.add(mCompany);

        mItem.setText("Item");

        jMenuItem9.setText("Stocks");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        mItem.add(jMenuItem9);

        jMenu1.setText("Product");

        jMenuItem1.setText("Add");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem10.setText("View / Update");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        mItem.add(jMenu1);

        jMenuBar1.add(mItem);

        mPurchase.setText("Purchase");

        jMenuItem3.setText("New Purchase");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mPurchase.add(jMenuItem3);

        jMenuItem4.setText("New Supplier");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mPurchase.add(jMenuItem4);

        jMenuItem7.setText("Barcodes");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        mPurchase.add(jMenuItem7);

        jMenuBar1.add(mPurchase);

        mSales.setText("Sales");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem2.setText("New Sale");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mSales.add(jMenuItem2);

        jMenuItem5.setText("Mini Statment");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mSales.add(jMenuItem5);

        jMenuBar1.add(mSales);

        mReturn.setText("Return");
        jMenuBar1.add(mReturn);

        mLedger.setText("Ledger");
        jMenuBar1.add(mLedger);

        jMenu7.setText("Help");
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlConteiner, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlConteiner, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        openNewProduct();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        openNewSale();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        openNewPurchase();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        openNewSupplier();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        openMiniStatmet();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        openLogin();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        openBarcodes();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Utilities.openDrower();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        openStocks();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        openItemList();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu7;
    public javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu mCompany;
    private javax.swing.JMenu mItem;
    private javax.swing.JMenu mLedger;
    private javax.swing.JMenu mPurchase;
    private javax.swing.JMenu mReturn;
    private javax.swing.JMenu mSales;
    public javax.swing.JPanel pnlConteiner;
    // End of variables declaration//GEN-END:variables

    public void setUser(User mUser) {
        this.mUser = mUser;
    }

    public void openNewProduct() {
        if (mUser != null) {
            new UIProductAdd(this).setVisible(true);
        } else {
            pnlConteiner.removeAll();
            pnlConteiner.add(new UILogin(this));
            pnlConteiner.revalidate();
        }
    }

    public void openNewSale() {
        if (mUser != null) {
            pnlConteiner.removeAll();
            UISale uiSale = new UISale(this);
            pnlConteiner.add(uiSale);
            pnlConteiner.revalidate();
            uiSale.changeForcuse();
        } else {
            pnlConteiner.removeAll();
            pnlConteiner.add(new UILogin(this));
            pnlConteiner.revalidate();
        }
    }

    private void openNewPurchase() {
        if (mUser != null) {
            pnlConteiner.removeAll();
            pnlConteiner.add(new UIGrn(this));
            pnlConteiner.revalidate();
        } else {
            pnlConteiner.removeAll();
            pnlConteiner.add(new UILogin(this));
            pnlConteiner.revalidate();
        }
    }

    public void openNewSupplier() {
        if (mUser != null) {
            new UISupplier(this).setVisible(true);
        } else {
            pnlConteiner.removeAll();
            pnlConteiner.add(new UILogin(this));
            pnlConteiner.revalidate();
        }
    }

    public User getUser() {
        return this.mUser;
    }

    private void openMiniStatmet() {
        if (mUser != null) {
            pnlConteiner.removeAll();
            pnlConteiner.add(new UIMiniStatment(this));
            pnlConteiner.revalidate();
        } else {
            pnlConteiner.removeAll();
            pnlConteiner.add(new UILogin(this));
            pnlConteiner.revalidate();
        }
    }

    private void openBarcodes() {
        if (mUser != null) {
            pnlConteiner.removeAll();
            pnlConteiner.add(new UIBarcode(this));
            pnlConteiner.revalidate();
        } else {
            pnlConteiner.removeAll();
            pnlConteiner.add(new UILogin(this));
            pnlConteiner.revalidate();
        }
    }

    private void openLogin() {
        setUser(null);
        if (mUser == null) {
            pnlConteiner.removeAll();
            pnlConteiner.add(new UILogin(this));
            pnlConteiner.revalidate();
        }
    }

    private void openStocks() {
        if (mUser != null) {
            pnlConteiner.removeAll();
            pnlConteiner.add(new UIStocks(this));
            pnlConteiner.revalidate();
        } else {
            pnlConteiner.removeAll();
            pnlConteiner.add(new UILogin(this));
            pnlConteiner.revalidate();
        }
    }

    private void openItemList() {
        if (mUser != null) {
            pnlConteiner.removeAll();
            pnlConteiner.add(new UIProductView(this));
            pnlConteiner.revalidate();
        } else {
            pnlConteiner.removeAll();
            pnlConteiner.add(new UILogin(this));
            pnlConteiner.revalidate();
        }
    }
}
